# Nome que aparecerá na aba "Actions" do GitHub
name: CI

# Quando executar este workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    # Máquina virtual criada pelo GitHub para executar o workflow
    runs-on: ubuntu-latest

    steps:
      # Faz o download (checkout) do código do repositório
      - name: Baixar o código
        uses: actions/checkout@v4

      # Instala o SDK do .NET na máquina do GitHub
      - name: Instalar .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      # Restaura todos os pacotes NuGet do projeto
      - name: Restaurar dependências da API
        working-directory: ./backEnd/Ci-Cd-Count/Ci-Cd-Count
        # rodando o comando especificando o local
        run: dotnet restore

      # Compila a aplicação para verificar se não há erros
      - name: Compilar API
        working-directory: ./backEnd/Ci-Cd-Count/Ci-Cd-Count
        run: dotnet build --no-restore


      # rodando os testes da nossa API  
      - name: Rodar testes
        run: dotnet test ./backEnd/Ci-Cd-Count/UNIT-CI-CD/UNIT-CI-CD.csproj --no-build

        # passos do front-end

      - name: Mostrar estrutura do repositório
        run: |
          pwd
          ls -la
          find .

      - name: Instalar Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: "./frontEnd/front/package-lock.json"
          # faz com q ele procure o package.json para colocar as dependencias, mas precisa dizer onde ele está, se n vai na raiz do projeto

      #             Glob (**)
      # cache-dependency-path: '**/package-lock.json'

      # ✅ Muito usado em monorepos grandes.

      - name: Instalar dependências do Front
        working-directory: ./frontEnd/front
        run: npm ci

      - name: Build do Front
        working-directory: ./frontEnd/front
        run: npm run build

      